version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.11  # Use Python 3.11 here
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.txt
version: 2.1
orbs:
  python: circleci/python@2
jobs:
  test-python:
    docker:
      - image: cimg/python:3.11  # Use Python 3.11 here
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: pip install -r requirements.tx  build-and-test:
    jobs:
      - test-python